name: Backend CD Pipeline

on:
  workflow_run:
    workflows: ['Backend CI Pipeline']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          timeout: 300s  # 5 minutes for Docker operations
          script: |
            echo "🚀 Starting backend deployment..."
            echo "SSH connection successful."
            
            echo "Pruning Docker system to remove unused containers, networks, images, and volumes..."
            docker system prune -a --volumes -f
            
            echo "Stopping and removing old container..."
            CONTAINER_ID=$(docker ps -a -q -f name=poultrypal-backend-container)
            if [ -n "$CONTAINER_ID" ]; then
              docker stop "$CONTAINER_ID"
              docker rm -f "$CONTAINER_ID"
            else
              echo "No old container to remove."
            fi
            
            echo "Deleting Docker image with tag latest..."
            IMAGE_ID=$(docker images -q danielofthechange/poultrypal-backend:latest)
            if [ -n "$IMAGE_ID" ]; then
              docker rmi -f "$IMAGE_ID"
            else
              echo "No image with tag latest to remove."
            fi
            
            echo "Pulling new Docker image..."
            docker pull danielofthechange/poultrypal-backend:latest
            
            echo "Running new Docker container..."
            docker run -d -p 3000:3000 --name poultrypal-backend-container danielofthechange/poultrypal-backend:latest
            
            echo "✅ Backend deployment completed!"
            echo "📊 Container status:"
            docker ps --filter name=poultrypal-backend-container