name: Backend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: cd API && docker build -t danielofthechange/poultrypal-backend .

      - name: Add latest tag to image
        run: docker tag danielofthechange/poultrypal-backend danielofthechange/poultrypal-backend:latest

      - name: Push to Dockerhub
        run: docker push danielofthechange/poultrypal-backend:latest